### ISSUE TITLE
Do not hardcode versions in the requirements.txt

### ISSUE THREAD

**Issue by mathbunnyru** [qchateau/conan-center-bot#12]
Right now if I install the package, it will downgrade my conan version to 1.30.2
It also requires idna==2.10 while conan requires idna==2.6

**Comment by qchateau** [comment]
I've taken the habit to hardcode versions in requirements.txt after my packages broke times and times again because pypi is maintained by the community and it happens that people publish broken packages. A quick google search seem to confirm many people share my point of view, what do you think ?

Though I agree that hardcoding the conan version is bad.

If you think it's fine I'll cleanup the requirements.txt file to leave only the "root" dependencies, and hardcode their versions, except for conan

**Comment by mathbunnyru** [comment]
I do like the approach of conan itself.

They have a range of supported versions:
https://github.com/conan-io/conan/blob/develop/conans/requirements.txt

As far as I see, they do not allow new major versions like this: `PyYAML>=3.11, <6.0`
PyYAML 6 is not released, but conan will update it as soon as they are ready to the updated version.

And at the same time if some version breaks they do add the rule to not to use this version:
https://github.com/conan-io/conan/pull/8042


But I need to tell you that I'm no python expert.

**Comment by qchateau** [comment]
I guess it makes sense to take conan's approach as this is a tool for conan. I'll do that

**Comment by qchateau** [comment]
I disabled new majors, but did not set a minimal version, not that I don't want to, but I don't want to spend time "finding" the minimum version for each dependency

**Comment by mathbunnyru** [comment]
Seems to work fine now.
